version: "3.3"
services:
  app:
    image: cshr/rpg-candidate-interface-ui:${DOCKER_SERVICE_TAG}
    ports:
      - "3000:3000"
    environment:
      API_URL: "${API_URL}"
      API_PORT: "${API_PORT}"
    networks:
      - cshr-net

networks:
  cshr-net:
    external: true