version: 2
jobs:
  build:
    environment:
      - COMPOSE_FILE: "docker-compose.yml"
      - BINTRAY_URL: "cshr-docker-rpg.bintray.io"
    machine: true
    steps:
      - checkout

      - run:
          name: Build image
          command: |
            cp .env.sample .env
            export DOCKER_SERVICE_TAG="$CIRCLE_WORKFLOW_ID"
            docker-compose build

      - run:
          name: Login to Bintray
          command: docker login -u cshr -p ${BINTRAY_API_KEY} ${BINTRAY_URL}

      - run:
          name: Push the images to Bintray
          command: docker push ${BINTRAY_URL}/rpg-candidate-interface-ui:${CIRCLE_WORKFLOW_ID}

  ship:
    environment:
      - COMPOSE_FILE: "docker-compose.yml"
    machine: true
    steps:
      - checkout

      - run:
          name: Login to Bintray
          command: docker login -u cshr -p ${BINTRAY_API_KEY} ${BINTRAY_URL}

      - run:
          name: Pull Current workflow images
          command: |
            cp .env.sample .env
            export DOCKER_SERVICE_TAG="$CIRCLE_WORKFLOW_ID"
            docker-compose pull
            images=$(docker images | grep "$DOCKER_SERVICE_TAG" | cut -d " " -f1)
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              docker_tag="latest"
            else
              docker_tag="$CIRCLE_BRANCH"
            fi
            for image in $images
            do
              docker tag "${image}":"${DOCKER_SERVICE_TAG}" "${image}":"${docker_tag}"
              docker push "${image}":"${docker_tag}"
            done

  notify_pipeline:
    machine: true
    steps:
      - run:
        name: Notify Jenkins pipeline to deploy change
        command: curl -X POST --user "circleci:${JENKINS_API_KEY}"  "https://${JENKINS_HOST}/job/deploy-rpg-candidate-interface-ui/buildWithParameters?dockerTag=${CIRCLE_WORKFLOW_ID}&environment=dev"


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - ship:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
      - notify_pipeline:
          requires:
            - ship
          filters:
            branches:
              only:
                - develop
