version: 2
jobs:
  build:
    environment:
      - COMPOSE_FILE: "docker-compose.yml"
    machine: true
    steps:
      - checkout

      - run:
          name: Build image
          command: |
            export DOCKER_SERVICE_TAG="$CIRCLE_WORKFLOW_ID"
            docker-compose build

      - run:
          name: Login to Docker Hub
          command: docker login -u $HUB_USERNAME -p $HUB_PASSWORD

      - run:
          name: Tag and push images
          command: |
            export DOCKER_SERVICE_TAG="$CIRCLE_WORKFLOW_ID"
            docker-compose push

  ship:
    environment:
      - COMPOSE_FILE: "docker-compose.yml"
      - DOCKER_SERVICE_TAG: "${CIRCLE_WORKFLOW_ID}"
    machine: true
    steps:
      - run:
          name: Login to Docker Hub
          command: docker login -u $HUB_USERNAME -p $HUB_PASSWORD

      - run:
          name: Pull Current workflow images
          command: |
            docker-compose pull
            images=$(docker images | grep "$DOCKER_SERVICE_TAG" | cut -d " " -f1)
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              docker_tag="latest"
            else
              docker_tag="$CIRCLE_BRANCH"
            fi
            for image in $images
            do
              docker tag "${image}":"${DOCKER_SERVICE_TAG}" "${image}":"${docker_tag}"
              docker push "${image}":"${docker_tag}"
            done

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - ship:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - develop
